name: monsda
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - biopython=1.83
  - grep >=3.4
  - isort=5.13.2
  - natsort=8.4.0
  - nextflow=24.10.0
  - numpy=1.26.4
  - pandas=2.2.1
  - perl=5.32.0
  - pip>=24.0
  - python=3.12.2
  - pyyaml=6.0.1
  - scipy=1.12.0
  - snakemake=8.25.5
  - snakemake-executor-plugin-slurm=0.11.2
  - snakemake-executor-plugin-cluster-generic=1.0.9
  - snakemake-interface-common=1.17.4
  - snakemake-interface-executor-plugins=9.3.2
  - snakemake-interface-report-plugins=1.1.0
  - snakemake-interface-storage-plugins=3.3.0
  - snakemake-storage-plugin-s3=0.2.12
  - snakemake-storage-plugin-ftp=0.1.2
  - snakemake-storage-plugin-sftp=0.1.2
  - snakemake-storage-plugin-http=0.2.3
  - snakemake-storage-plugin-zenodo=0.1.4