name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install build dependencies
      run: |
        conda activate monsda
        python -m pip install --upgrade pip
        pip install build

    - name: Build the project
      run: |
        conda activate monsda
        python -m build

    - name: Install the package
      run: |
        conda activate monsda
        pip install dist/*.whl

    - name: Run tests
      run: |
        conda activate monsda
        bash tests/cicd_test.sh