name: Python application

on: [push, pull_request]

jobs:
  monsdatest:   
    name: monsda-test 
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    # Docker Hub image that `postgres-job` executes in
    container: node:latest
    # service containers to run with `postgres-job`
    steps:      
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@master
        with:
          miniconda-version: "latest"
          activate-environment: monsda-test
          environment-file: environment.yml
          python-version: 3.12.2
          channels: conda-forge,bioconda
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: false
          auto-activate-base: false
      - name: Run tests
        run: |
          echo "Build start" 
          git config user.name "Testuser"
          git config user.email "test@nomailforthisuser.com"          
          git tag -f "test"             
          python -m pip install --upgrade pip                
          python -m pip install build
          #echo -e '[egg_info]\ntag_build=.test+monsda\n' > /tmp/build_opts.cfg
          #DIST_EXTRA_CONFIG=/tmp/build_opts.cfg python -m build   
          python -m build          
          pip install dist/*.whl
          echo $PATH
          monsda --version          
          echo "Build finished, starting tests"          
          bash tests/cicd_test.sh