name: Python application

on: [push, pull_request]

jobs:
  monsdatest:   
    name: monsda-test 
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    # Docker Hub image that `postgres-job` executes in
    container: node:latest
    # service containers to run with `postgres-job`
    steps:      
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@master
        with:
          miniconda-version: "latest"
          activate-environment: monsda-test
          environment-file: environment.yml
          python-version: 3.12.2
          channels: conda-forge,bioconda
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: false
          auto-activate-base: false
      - name: Run tests
        run: |
          echo "Build start" 
          git config user.name "Testuser"
          git config user.email "test@nomailforthisuser.com"                    
          python -m pip install --upgrade pip                
          python -m pip install build                                        
          python -m build
          pip install dist/*.whl          
          monsda --version 2> /tmp/monsda_version.txt
          a=$(cat /tmp/monsda_version.txt |sed 's/MONSDA version //g'); sed -i 's/"VERSION": "FIXME"/"VERSION": "'$a'"/g' tests/data/config_Test.json
          head tests/data/config_Test.json
          echo "Build finished, starting tests"          
          bash tests/cicd_test.sh